FROM marvinpan/python:alpine
MAINTAINER marvinpan <pantj@investoday.com.cn>
RUN pip3 install --default-timeout=100 --no-cache-dir --upgrade apscheduler flasgger flask_cors flask_compress redis pymongo sqlalchemy mysql-connector flask_apscheduler

